apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-np
spec:
  type: NodePort
  ports:
    - port: 30000
      name: cql
      nodePort: 30000
  selector:
    app: cassandra
