apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra-3
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
  # labels:
    # app: cassandra
spec:
  replicas: 1
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  # selector:
      # app: cassandra
  template:
    metadata:
      labels:
        app: cassandra-3
    spec:
      containers:
        - env:
            - name: CASSANDRA_SEEDS
              value: 172.17.13.151
            - name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: Rack1
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: CASSANDRA_BROADCAST_ADDRESS
              value: 172.17.13.201
            - name: CASSANDRA_NATIVE_PORT
              value: "30002"
          image: docker.io/decomads/cassandra:2.0
          name: cassandra
          ports:
            - containerPort: 7000
              name: intra-node
              hostPort: 7000
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
              hostPort: 7199
            - containerPort: 30002
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: data
      nodeSelector:
        cassandraHost-3: "true"
      volumes:
        - name: data
          hostPath: 
            path: /cassandra/db
