# db-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller-node-port
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-node-port
    spec:
      containers:
      - image: mongo:3.2.4
        name: mongo
        command:
            - mongod
            - "--logappend"
            - "--logpath"
            - /var/log/mongodb/mongod.log
            - "--bind_ip"
            - 0.0.0.0
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mypd
      nodeSelector:
        version: nodeport
      volumes:
        - name: mypd
          hostPath:
            path: /data/db
             
