#!/bin/bash

#argument $1 = name of experiment
#output: csv file generated by dstat with as name $1-`hostname`.csv
l=${#1}
if (( l==0 )); then 
  echo no experiment identifier 
  exit
fi
files=`ls`
filename=$1-`hostname`.csv
if [[ $files =~ .*$filename.* ]] ; then
  echo file $filename already exists
  exit
fi

dstat -T -t -cp  -mgs --vm -r -d  -D total --fs --lock  -N eth0 --socket  --ipc  -y --noheaders --output $filename --noupdate 5  > /dev/null
