#!/bin/bash

#argument $1 = name of experiment
#argument $2 = specific network interface that must be monitored
#output: csv file generated by dstat with as name $1-`hostname`.csv
l=${#1}
if (( l==0 )); then 
  echo no experiment identifier 
  exit
fi
files=`ls`
filename=$1_NET-$2-`hostname`.csv
if [[ $files =~ .*$filename.* ]] ; then
  echo file $filename already exists
  exit
fi

dstat -T -t -N $2 --output $filename --noheaders --noupdate 5
