kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim-dynamic
  annotations:
    volume.beta.kubernetes.io/storage-class: "gold"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
