# db-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-nodeport-flocker
  name: mongo-controller-nodeport-flocker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-nodeport-flocker
    spec:
      containers:
      - image: mongo:3.2.4
        name: mongo
        command:
            - mongod
            - "--logappend"
            - "--logpath"
            - /var/log/mongodb/mongod.log
            - "--bind_ip"
            - 0.0.0.0
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mypd
      nodeSelector:
        version: nodeport_flocker
      volumes:
        - name: mypd
          persistentVolumeClaim:
             claimName: myclaim-1
