apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-3
  name: cassandra-np-3
spec:
  type: NodePort
  ports:
    - port: 30002
      name: cql
      nodePort: 30002
  selector:
    app: cassandra-3
