apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra-lb-sa
  name: cassandra-lb-sa
spec:
  ports:
    - port: 9042
      name: cql
  selector:
    name: cassandra
  type: LoadBalancer
  sessionAffinity: ClientIP
