apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-2
  name: cassandra-np-2
spec:
  type: NodePort
  ports:
    - port: 30001
      name: cql
      nodePort: 30001
  selector:
    app: cassandra-2
