apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-container-port
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-container-port
  type: ClusterIP
