apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-nodeport-flocker
  name: mongo-nodeport-flocker
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-nodeport-flocker
  type: NodePort
