apiVersion: v1
kind: Service
metadata:
  name: cassandra-db
  labels:
    app: cassandra-db
    tier: backend
    role: master
spec:
  ports:
  - port: 9160 
    targetPort: 9160
  selector:
    app: cassandra-db
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-db
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: cassandra
        env:
        - name: TZ
          value: "Europe/Brussels"
        - name: CASSANDRA_START_RPC 
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9160
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
    tier: backend
    role: master
spec:
  ports:
  - port: 27017 
    targetPort: 27017
  selector:
    app: mongo-db
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: mongo
        env:
        - name: TZ
          value: "Europe/Brussels"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: lmaas
  labels:
    run: lmaas
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    run: lmaas
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lmaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: lmaas
    spec:
      containers:
      - name: lmaas
        image: t138/lmaas
        ports:
        - containerPort: 8080
