version: '3'
services:
  cassandra-1:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-1]
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-1
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
    - volume1:/var/lib/cassandra
    ports:
    - "7000"
    - "7001"
    - "7199"
    - "9042"
    networks:
      default:
  cassandra-2:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-2]
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-2
      CASSANDRA_SEEDS: cassandra-1
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    depends_on:
      - cassandra-1
    volumes:
    - volume2:/var/lib/cassandra
    ports:
    - "7000"
    - "7001"
    - "7199"
    - "9042" 
    networks:
      default:
  cassandra-3:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-3]
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-3
      CASSANDRA_SEEDS: cassandra-1
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    depends_on:
      - cassandra-2
    volumes:
    - volume3:/var/lib/cassandra
    ports:
    - "7000"
    - "7001"
    - "7199"
    - "9042"
    networks:
      default:
volumes:
  volume1:
    driver: local
  volume2:
    driver: local
  volume3:
    driver: local
networks:
  default:
    external:
       name: cassandra-net
