apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 200m
      memory: 500Mi
    type: Pod
  - default:
      cpu: "2"
      memory: 2Gi
    defaultRequest:
      cpu: "1"
      memory: 1Gi
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 200m
      memory: 500Mi
    type: Container
