# db-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ycsb
  name: ycsb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ycsb
    spec:
      containers:
      - image: decomads/ycsb-middleware2017
        name: ycsb
        command:
            - start.sh
        volumeMounts:
        - mountPath: /results
          name: mypd
      nodeSelector:
        ycsb-node: "true"
      volumes:
        - name: mypd
          hostPath:
            path: /data/results
             
