apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "12"
    replicationcontrollers: "3"
    secrets: "10"
    services: "10"
