version: '3'
services:
  cassandra-1:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-1]
#    entrypoint:
#    - "sh"
#    - "-c"
#    - sed -i "s/ 0.0.0.0/ 172.17.13.151/" /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh cassandra -f
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 172.17.13.151
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
    - volume1:/var/lib/cassandra
    ports:
    - "7000:7000"
    - "7001"
    - "7199"
    - "9042:9042"
    - "9160:9160"
#    - target: 7000
#      mode: ingress
#      protocol: tcp
#    - target: 7001
#      mode: ingress
#      protocol: tcp
#    - target: 7199
#      mode: ingress
#      protocol: tcp
#    - target: 9042
#      mode: ingress
#      protocol: tcp
  cassandra-2:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-2]
    entrypoint:
    - "sh"
    - "-c"
    - sed -i "s/ 7000/ 7011/" "s/ 0.0.0.0/ 172.17.13.154/" /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh cassandra -f
#    command: sed -i "s/ 7000/ 7011/" /etc/cassandra/cassandra.yaml; cassandra -f; 
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 172.17.13.154
      CASSANDRA_SEEDS: 172.17.13.151
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    depends_on:
      - cassandra-1
    volumes:
    - volume2:/var/lib/cassandra
    ports:
    - "7011:7011"
    - "7001"
    - "7199"
    - "9043:9043"
  cassandra-3:
    image: cassandra:2.0
    deploy:
      placement:
        constraints: [node.hostname == docker-swarm-worker-3]
    entrypoint: 
    - "sh"
    - "-c"
    - sed -i "s/ 7000/ 7012/" "s/ 0.0.0.0/ 172.17.13.201/" /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh cassandra -f
#   command: sed -i "s/ 7000/ 7012/" /etc/cassandra/cassandra.yaml; cassandra -f;
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 172.17.13.201
      CASSANDRA_SEEDS: 172.17.13.151
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    depends_on:
      - cassandra-2
    volumes:
    - volume3:/var/lib/cassandra
    ports:
    - "7012:7012"
    - "7001"
    - "7199"
    - "9044:9044"
volumes:
  volume1:
    driver: local
  volume2:
    driver: local
  volume3:
    driver: local
