apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
spec:
  limits:
  - max:
      cpu: 125m
      memory: 512Mi
    min:
      cpu: 125m
      memory: 512Mi
    type: Pod
  - default:
      cpu: 125m
      memory: 512Mi
    defaultRequest:
      cpu: 125m
      memory: 512Mi
    max:
      cpu: 125m
      memory: 512Mi
    min:
      cpu: 125m
      memory: 512Mi
    type: Container
